Send pandoc error messages to notify-send
If pandoc has a nonzero exit value, then send its staderr to our
'error' function, which will display the message using notify-send if
necessary.

Now GUI users get a readable error message if they do things like
double-click on a markdown file to which they do not have read access,
or anything else pandoc has trouble with.

diff --git a/watch-markdown b/watch-markdown
--- a/watch-markdown
+++ b/watch-markdown
@@ -69,7 +69,13 @@ fi
 function convert {
     # Convert the given markdown file to an HTML file
     css="$HOME/.config/watch-markdown/github.css"
-    pandoc --standalone -c "$css" "$in" -o "$out"
+    set +e
+    output=$(pandoc --standalone -c "$css" "$in" -o "$out" 2>&1)
+    exitval=$?
+    set -e
+    if [[ $exitval -ne 0 ]] ; then
+        error "$exitval" "watch-markdown ERROR" "$output"
+    fi
 }
 
 convert
